# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btoken.proto\x12\x05token\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\rTokenResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2J\n\x0cTokenService\x12:\n\rExchangeToken\x12\x13.token.TokenRequest\x1a\x14.token.TokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENREQUEST']._serialized_start=22
  _globals['_TOKENREQUEST']._serialized_end=51
  _globals['_TOKENRESPONSE']._serialized_start=53
  _globals['_TOKENRESPONSE']._serialized_end=82
  _globals['_TOKENSERVICE']._serialized_start=84
  _globals['_TOKENSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
